### ISSUE TITLE
Feat: working on dashboard design page

### ISSUE THREAD

**Issue by amuza2** [devunionorg/PetFinderASPCoreMVC#6]
Working on dashboard design page
taking this page as an inspiration

![Image](https://github.com/devunionorg/PetFinderASPCoreMVC/assets/16819120/cb7098b7-5c11-44f0-92cd-c93c612d83e8)

**Comment by abdelillahbel** [comment]
##### gg @amuza2

**Comment by abdelillahbel** [comment]
## راك راقد ا لحاج 🙂🙂🙂🙂🙂🙂🙂 @amuza2  #####

**Comment by abdelillahbel** [comment]
> ## راك راقد ا لحاج 🙂🙂🙂🙂🙂🙂🙂 @amuza2

## @Benraouf93 see this
